[package]
name = "embedded-controls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
switch-hal = "^0.4.0"
num = "^0.4.0"
